application: minipcs-777
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: core/static/favicon.ico
  upload: core/static/favicon\.ico

- url: /static(.*)
  static_files: core/static\1
  upload: core/static.*

- url: .*
  script: core.main.app
